
import React, { useState, useEffect, useMemo, useRef } from 'react';
import type { Student, Activity } from './types';
import { Status, teams, schoolSections, initiators } from './types';
import StudentForm from './components/StudentForm';
import StudentTable from './components/StudentTable';
import GeminiAnalysisModal from './components/GeminiAnalysisModal';
import Sidebar from './components/Sidebar';
import AnalyticsDashboard from './components/AnalyticsDashboard';
import LoginScreen from './components/LoginScreen';
import Activities from './components/Activities';
import TeamTasks from './components/TeamTasks';
import { MenuIcon, SparklesIcon, UsersIcon, ChartBarIcon, HomeIcon, FunnelIcon, ArrowPathIcon, UserPlusIcon, SunIcon, MoonIcon, ExclamationCircleIcon, EnvelopeIcon, LoaderIcon, CheckCircleIcon, ClipboardDocumentListIcon } from './components/icons';

// --- CONFIGURATION ---
const STORAGE_KEY_USER = 'cms_user_session_v1';
const API_BASE_URL = import.meta.env.PROD ? '/api' : 'http://localhost:5000/api'; // Production uses relative API calls
const ADMIN_USERS = ['praveen_k@lmes.in', 'support@lmes.in'];

// Helper to generate HTML table for emails
const generateEmailTable = (students: Student[], title: string, agentName: string) => {
    const rows = students.map(s => `
        <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">${s.studentName}</td>
            <td style="padding: 8px; border: 1px solid #ddd;">${s.phoneNumber || '-'}</td>
            <td style="padding: 8px; border: 1px solid #ddd;">${s.category}</td>
            <td style="padding: 8px; border: 1px solid #ddd;">${s.reasonToHold || 'N/A'}</td>
            <td style="padding: 8px; border: 1px solid #ddd;">${s.reminderDate}</td>
        </tr>
    `).join('');

    return `
        <div style="font-family: Arial, sans-serif;">
            <h2 style="color: #6d28d9;">Hello ${agentName},</h2>
            <p>You have pending follow-ups for the following students as of <strong>${title}</strong>:</p>
            <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
                <thead>
                    <tr style="background-color: #f3f4f6;">
                        <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Name</th>
                        <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Phone</th>
                        <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Category</th>
                        <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Reason</th>
                        <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Reminder Date</th>
                    </tr>
                </thead>
                <tbody>
                    ${rows}
                </tbody>
            </table>
            <p style="margin-top: 20px; font-size: 12px; color: #666;">Generated by CMS Tracker System</p>
        </div>
    `;
};

const App = () => {
  // --- State Management ---
  const [students, setStudents] = useState<Student[]>([]);
  const [activities, setActivities] = useState<Activity[]>([]);
  
  // User session is still kept in LocalStorage for persistence across refreshes
  const [user, setUser] = useState<string | null>(() => {
      return localStorage.getItem(STORAGE_KEY_USER);
  });

  const [isMobileOpen, setIsMobileOpen] = useState(false);
  const [activeSegment, setActiveSegment] = useState('Dashboard');
  const [darkMode, setDarkMode] = useState(false);
  
  const [selectedStudentForAnalysis, setSelectedStudentForAnalysis] = useState<Student | null>(null);
  const [studentToEdit, setStudentToEdit] = useState<Student | null>(null);
  
  // UI Feedback State
  const [notification, setNotification] = useState<{message: string, type: 'success' | 'error'} | null>(null);
  const [isSendingEmail, setIsSendingEmail] = useState(false);
  const [dbError, setDbError] = useState(false);

  const isAdmin = user && ADMIN_USERS.includes(user.toLowerCase());

  // --- Data Fetching ---
  const fetchData = async () => {
      try {
          const [studentsRes, activitiesRes] = await Promise.all([
              fetch(`${API_BASE_URL}/students`),
              fetch(`${API_BASE_URL}/activities`)
          ]);

          if (!studentsRes.ok || !activitiesRes.ok) throw new Error('Failed to fetch data');

          const studentsData = await studentsRes.json();
          const activitiesData = await activitiesRes.json();

          setStudents(studentsData);
          setActivities(activitiesData);
          setDbError(false);
      } catch (error) {
          console.error("Database connection failed:", error);
          setDbError(true);
      }
  };

  useEffect(() => {
      if (user) {
          fetchData();
      }
  }, [user]);

  useEffect(() => {
    if (user) {
      localStorage.setItem(STORAGE_KEY_USER, user);
    } else {
      localStorage.removeItem(STORAGE_KEY_USER);
    }
  }, [user]);

  useEffect(() => {
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
      setDarkMode(true);
    }
  }, []);

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  useEffect(() => {
    if (notification) {
      const timer = setTimeout(() => setNotification(null), 10000); 
      return () => clearTimeout(timer);
    }
  }, [notification]);

  // --- Derived Data for Security ---
  const viewableStudents = useMemo(() => {
      if (!user) return [];
      if (isAdmin) {
          return students;
      }
      return students.filter(s => s.createdByEmail === user);
  }, [students, user, isAdmin]);

  // --- Actions ---

  const logActivity = async (action: Activity['action'], details: string, specificUser?: string) => {
    const actor = specificUser || user;
    if (!actor) return;

    const newActivity = {
      id: Date.now().toString(),
      user: actor,
      action,
      details,
      timestamp: new Date().toLocaleString()
    };

    try {
        await fetch(`${API_BASE_URL}/activities`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(newActivity)
        });
        // Optimistic update
        setActivities(prev => [newActivity as Activity, ...prev]);
    } catch (e) {
        console.error("Failed to log activity", e);
    }
  };

  const handleLogin = (email: string) => {
    setUser(email);
    logActivity('LOGIN', 'User logged in successfully', email);
  };

  const handleLogout = () => {
    logActivity('LOGOUT', 'User logged out');
    setUser(null);
    setActiveSegment('Dashboard');
    setStudents([]);
    setActivities([]);
  };

  const handleAddStudent = async (newStudent: Student) => {
    const studentWithUser = {
        ...newStudent,
        createdByEmail: user || 'unknown',
    };
    
    try {
        const res = await fetch(`${API_BASE_URL}/students`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(studentWithUser)
        });

        if (!res.ok) throw new Error('Failed to save student');

        const savedStudent = await res.json();
        setStudents(prev => [savedStudent, ...prev]);
        logActivity('ADD_STUDENT', `Added student: ${newStudent.studentName}`);
        setActiveSegment('All Students');
        setNotification({ message: 'Student added successfully', type: 'success' });
        
        // Send reminder for the new student
        handleSendManualReminders([savedStudent], 'New Student Reminder');

    } catch (e) {
        setNotification({ message: 'Error saving student to server', type: 'error' });
    }
  };

  const handleEditStudent = (student: Student) => {
      setStudentToEdit(student);
      setActiveSegment('Edit Student');
  };

  const handleUpdateStudent = async (updatedStudent: Student) => {
      try {
          const res = await fetch(`${API_BASE_URL}/students/${updatedStudent.id}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(updatedStudent)
          });

          if (!res.ok) throw new Error('Failed to update student');
          
          setStudents(prev => prev.map(s => s.id === updatedStudent.id ? updatedStudent : s));
          logActivity('EDIT_STUDENT', `Updated student details: ${updatedStudent.studentName}`);
          setStudentToEdit(null);
          setActiveSegment('All Students');
          setNotification({ message: 'Student updated successfully', type: 'success' });
      } catch (e) {
          setNotification({ message: 'Error updating student on server', type: 'error' });
      }
  };

  const handleDeleteStudent = async (id: string) => {
    const studentToDelete = students.find(s => s.id === id);
    if (studentToDelete) {
        try {
            const res = await fetch(`${API_BASE_URL}/students/${id}`, { method: 'DELETE' });
            if (!res.ok) throw new Error('Failed to delete');

            setStudents(prev => prev.filter(s => s.id !== id));
            logActivity('DELETE_STUDENT', `Deleted student: ${studentToDelete.studentName}`);
            setNotification({ message: 'Student deleted', type: 'success' });
        } catch (e) {
             setNotification({ message: 'Error deleting student on server', type: 'error' });
        }
    }
  };

  const handleToggleReminder = async (student: Student) => {
      const updated = { ...student, stopReminders: !student.stopReminders };
      try {
          await fetch(`${API_BASE_URL}/students/${student.id}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(updated)
          });
          
          setStudents(prev => prev.map(s => s.id === student.id ? updated : s));
          const status = updated.stopReminders ? 'stopped' : 'activated';
          logActivity('TOGGLE_REMINDER', `Auto-reminders ${status} for: ${student.studentName}`);
          setNotification({ message: `Auto-reminders ${status} for ${student.studentName}`, type: 'success'});
      } catch (e) {
          setNotification({ message: 'Failed to toggle reminder', type: 'error' });
      }
  };

  // --- Email Logic (Server-Side) ---

  const sendEmailViaBackend = async (to: string, subject: string, htmlBody: string) => {
      const response = await fetch(`${API_BASE_URL}/send-email`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ to, subject, htmlBody })
      });
      if (!response.ok) {
          const err = await response.json();
          throw new Error(err.message || 'Failed to send email');
      }
      return response.json();
  };

  const handleSendManualReminders = async (studentsOverride?: Student[], autoLabel?: string) => {
    if (!user) return;
    
    const today = new Date().toISOString().split('T')[0];
    const reminders = studentsOverride || viewableStudents.filter(s => 
        s.reminderDate && 
        s.reminderDate <= today && 
        (s.status === Status.ON_HOLD || s.status === Status.PENDING)
    );

    if (reminders.length === 0) {
        if (!autoLabel) setNotification({ message: "No pending reminders found.", type: 'success' });
        return;
    }

    setIsSendingEmail(true);

    // Group tasks
    const tasksByAgent: Record<string, Student[]> = {};
    reminders.forEach(s => {
        const agent = s.initiatedBy || 'Unassigned';
        if (!tasksByAgent[agent]) tasksByAgent[agent] = [];
        tasksByAgent[agent].push(s);
    });

    let sentCount = 0;
    let failedCount = 0;
    const agents = Object.keys(tasksByAgent);

    for (const agentName of agents) {
        const agentTasks = tasksByAgent[agentName];
        const agentInfo = initiators.find(i => i.name === agentName);

        if (!agentInfo || !agentInfo.email || !agentInfo.email.includes('@')) {
            console.warn(`No email found for agent: ${agentName}`);
            failedCount++;
            continue;
        }

        const emailBody = generateEmailTable(agentTasks, new Date().toDateString(), agentName);
        const subject = `[Reminder] ${autoLabel || 'Action Required'} - Follow-ups for ${agentTasks.length} students`;

        try {
            await sendEmailViaBackend(agentInfo.email, subject, emailBody);
            sentCount++;
        } catch (err) {
            console.error(`Failed to send to ${agentName}`, err);
            failedCount++;
        }
    }

    if (autoLabel) {
            // Re-fetch to sync
            await fetchData();
            logActivity('SEND_EMAIL', `Auto-sent ${autoLabel} emails to ${sentCount} agents.`);
    } else {
            if (sentCount > 0) {
            logActivity('SEND_EMAIL', `Manual dispatch to ${sentCount} agents.`);
            setNotification({ message: `Emails sent to ${sentCount} agents.`, type: 'success' });
            }
            if (failedCount > 0) {
                setNotification({ message: `Failed to send to ${failedCount} agents. Check server logs.`, type: 'error' });
            }
    }
    setIsSendingEmail(false);
  };

  // --- Scheduler Hook (Client Side, triggers Server Side actions) ---
  useEffect(() => {
      const interval = setInterval(() => {
          if (!isAdmin) return;
          
          const now = new Date();
          const todayStr = now.toISOString().split('T')[0];
          
          const hour = now.getHours();
          const minutes = now.getMinutes();
          
          const isTenAMTrigger = hour === 10 && minutes >= 0 && minutes < 5;
          const isOnePMTrigger = hour === 13 && minutes >= 0 && minutes < 5;
          const isFourPMTrigger = hour === 16 && minutes >= 0 && minutes < 5;
          const isSixPMTrigger = hour === 18 && minutes >= 0 && minutes < 5;
          const isEightPMTrigger = hour === 20 && minutes >= 0 && minutes < 5;

          const pendingStudents = students.filter(s => !s.stopReminders && (s.status === Status.ON_HOLD || s.status === Status.PENDING));

          if (isTenAMTrigger) {
              const batch = pendingStudents.filter(s => s.reminderDate === todayStr);
              if (batch.length > 0) {
                  handleSendManualReminders(batch, '10:00 AM Reminder');
              }
          }

          if (isOnePMTrigger) {
               const batch = pendingStudents.filter(s => s.reminderDate === todayStr);
               if (batch.length > 0) {
                   handleSendManualReminders(batch, '1:00 PM Reminder');
               }
          }

          if (isFourPMTrigger) {
               const batch = pendingStudents.filter(s => s.reminderDate === todayStr);
               if (batch.length > 0) {
                   handleSendManualReminders(batch, '4:00 PM Reminder');
               }
          }

          if (isSixPMTrigger) {
               const batch = pendingStudents.filter(s => s.reminderDate === todayStr);
               if (batch.length > 0) {
                   handleSendManualReminders(batch, '6:00 PM Reminder');
               }
          }

          if (isEightPMTrigger) {
                const batch = pendingStudents.filter(s => s.reminderDate === todayStr);
                if (batch.length > 0) {
                    handleSendManualReminders(batch, '8:00 PM Reminder');
                }
          }

      }, 60000);

      return () => clearInterval(interval);
  }, [students, isAdmin]);

  // --- Render Logic ---

  if (!user) {
    return <LoginScreen onLogin={handleLogin} />;
  }

  if (dbError) {
      return (
          <div className="min-h-screen flex items-center justify-center bg-red-50 dark:bg-slate-900 p-4">
              <div className="max-w-md w-full bg-white dark:bg-slate-800 p-6 rounded-2xl shadow-lg border border-red-200 dark:border-red-900 text-center">
                  <ExclamationCircleIcon className="w-12 h-12 text-red-500 mx-auto mb-4" />
                  <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Server Connection Failed</h2>
                  <p className="text-slate-600 dark:text-slate-400 mb-6">
                      Could not connect to the backend server. Please ensure the server is running.
                  </p>
                  <code className="block bg-slate-100 dark:bg-slate-900 p-2 rounded text-xs mb-4">node server.js</code>
                  <button 
                    onClick={fetchData}
                    className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition"
                  >
                      Retry Connection
                  </button>
              </div>
          </div>
      )
  }

  const renderContent = () => {
    switch (activeSegment) {
      case 'Dashboard':
        return (
            <div className="space-y-8">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                    <div>
                        <h1 className="text-2xl font-bold text-slate-800 dark:text-white">
                            Welcome back, {user.split('@')[0]}
                        </h1>
                        <p className="text-slate-500 dark:text-slate-400 mt-1">
                            Here's what's happening with your tracked students today.
                        </p>
                    </div>
                    <div className="flex items-center gap-3">
                         <div className="px-4 py-2 bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 text-sm text-slate-600 dark:text-slate-300 shadow-sm flex items-center">
                            <span className="w-2 h-2 rounded-full bg-green-500 mr-2"></span>
                            {isAdmin ? 'Admin Access' : 'Standard Access'}
                         </div>
                    </div>
                </div>
                
                <AnalyticsDashboard students={viewableStudents} />
                {isAdmin && <TeamTasks students={viewableStudents} />}
            </div>
        );
      case 'All Students':
        return (
          <div className="space-y-6 animate-fade-in">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Student Directory</h2>
                <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
                  Manage and track all students. {isAdmin && "Auto-reminders active if tab is open."}
                </p>
              </div>
              
              <div className="flex gap-2">
                 {isAdmin && (
                    <button
                        onClick={() => handleSendManualReminders()}
                        disabled={isSendingEmail}
                        className="inline-flex items-center px-4 py-2 bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-600 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 dark:focus:ring-offset-slate-900 transition-colors shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {isSendingEmail ? (
                            <LoaderIcon className="w-4 h-4 mr-2 animate-spin text-purple-600" />
                        ) : (
                            <EnvelopeIcon className="w-4 h-4 mr-2 text-purple-600" />
                        )}
                        {isSendingEmail ? 'Dispatching...' : 'Send Reminders Now'}
                    </button>
                 )}
                 <button 
                    onClick={() => setActiveSegment('Add Student')}
                    className="inline-flex items-center px-4 py-2 bg-purple-600 border border-transparent rounded-lg text-sm font-medium text-white hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 shadow-md transition-transform hover:scale-105"
                  >
                    <UserPlusIcon className="w-4 h-4 mr-2" />
                    Add Student
                  </button>
              </div>
            </div>
            <StudentTable 
                students={viewableStudents} 
                onAnalyze={(s) => setSelectedStudentForAnalysis(s)} 
                onDelete={isAdmin ? handleDeleteStudent : undefined}
                onEdit={handleEditStudent}
                onToggleReminder={handleToggleReminder}
            />
          </div>
        );
      case 'Add Student':
        return (
          <div className="max-w-4xl mx-auto animate-fade-in">
            <div className="mb-8">
               <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Add New Student</h2>
               <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Create a new record for an on-hold student.</p>
            </div>
            <StudentForm 
              onAddStudent={handleAddStudent} 
              existingStudents={students} 
            />
          </div>
        );
      case 'Edit Student':
          return (
            <div className="max-w-4xl mx-auto animate-fade-in">
                <div className="mb-8 flex items-center justify-between">
                    <div>
                        <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Edit Student Record</h2>
                        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Update the details for this student.</p>
                    </div>
                    <button
                        onClick={() => setActiveSegment('All Students')}
                        className="text-sm text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-white"
                    >
                        Cancel
                    </button>
                </div>
                {studentToEdit ? (
                    <StudentForm 
                        initialData={studentToEdit}
                        onSave={handleUpdateStudent}
                        existingStudents={students}
                        isEditing={true}
                    />
                ) : (
                    <div className="text-red-500">Error: No student selected for editing.</div>
                )}
            </div>
          );
      case 'Activities':
          if (!isAdmin) return <div className="p-8 text-center text-slate-500">Access Denied</div>;
          return <Activities activities={activities} />;
      case 'Analytics':
        return <AnalyticsDashboard students={viewableStudents} />;
      case 'Settings':
        return (
            <div className="max-w-2xl mx-auto animate-fade-in space-y-6">
                 <div className="mb-6">
                    <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Settings</h2>
                    <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Manage your application preferences.</p>
                 </div>
                 
                 <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-6">
                    <h3 className="text-lg font-semibold text-slate-800 dark:text-white mb-4">Appearance</h3>
                    <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-3">
                            <div className={`p-2 rounded-lg ${darkMode ? 'bg-slate-700 text-slate-400' : 'bg-orange-100 text-orange-600'}`}>
                                {darkMode ? <MoonIcon className="w-6 h-6" /> : <SunIcon className="w-6 h-6" />}
                            </div>
                            <div>
                                <p className="font-medium text-slate-900 dark:text-slate-200">Dark Mode</p>
                                <p className="text-sm text-slate-500 dark:text-slate-400">Toggle between light and dark themes</p>
                            </div>
                        </div>
                        <button 
                            onClick={() => setDarkMode(!darkMode)}
                            className={`relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 ${darkMode ? 'bg-purple-600' : 'bg-slate-200'}`}
                        >
                            <span className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${darkMode ? 'translate-x-5' : 'translate-x-0'}`} />
                        </button>
                    </div>
                 </div>

                 <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-6">
                    <h3 className="text-lg font-semibold text-slate-800 dark:text-white mb-4">Account</h3>
                    <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-3">
                            <div className="w-10 h-10 rounded-full bg-purple-100 dark:bg-purple-900/50 flex items-center justify-center text-purple-700 dark:text-purple-300 font-bold">
                                {user.substring(0, 1).toUpperCase()}
                            </div>
                            <div>
                                <p className="font-medium text-slate-900 dark:text-slate-200">{user}</p>
                                <p className="text-sm text-slate-500 dark:text-slate-400">Currently logged in</p>
                            </div>
                        </div>
                        <button 
                            onClick={handleLogout}
                            className="px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 transition-colors"
                        >
                            Sign Out
                        </button>
                    </div>
                 </div>
            </div>
        );
      default:
        return <div className="p-10 text-center text-slate-500">Section under construction</div>;
    }
  };

  return (
    <div className={`flex h-screen bg-slate-50 dark:bg-slate-900 font-sans text-slate-900 dark:text-slate-100 transition-colors duration-200 ${darkMode ? 'dark' : ''}`}>
        
        <Sidebar 
            activeSegment={activeSegment} 
            onSelect={setActiveSegment} 
            isMobileOpen={isMobileOpen}
            onCloseMobile={() => setIsMobileOpen(false)}
            currentUser={user}
        />

        <div className="flex-1 flex flex-col md:pl-64 overflow-hidden">
            {/* Mobile Header */}
            <header className="md:hidden bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 p-4 flex items-center justify-between z-20">
                <div className="flex items-center space-x-2">
                     <div className="w-8 h-8 bg-purple-600 rounded-lg flex items-center justify-center">
                        <span className="text-white font-bold">C</span>
                    </div>
                    <h1 className="font-bold text-lg text-slate-800 dark:text-white">CMS Tracker</h1>
                </div>
                <button onClick={() => setIsMobileOpen(true)} className="p-2 text-slate-600 dark:text-slate-300">
                    <MenuIcon className="w-6 h-6" />
                </button>
            </header>

            {/* Main Content Area */}
            <main className="flex-1 overflow-y-auto p-4 md:p-8 scrollbar-thin scrollbar-thumb-slate-300 dark:scrollbar-thumb-slate-700">
                {renderContent()}
            </main>
        </div>

        {/* Global Modals */}
        <GeminiAnalysisModal 
            student={selectedStudentForAnalysis} 
            onClose={() => setSelectedStudentForAnalysis(null)} 
        />

        {/* Toast Notification */}
        {notification && (
            <div className={`fixed bottom-4 right-4 z-50 px-4 py-3 rounded-xl shadow-lg border flex items-center animate-bounce-in ${
                notification.type === 'success' 
                    ? 'bg-white dark:bg-slate-800 border-green-500 text-green-700 dark:text-green-400' 
                    : 'bg-white dark:bg-slate-800 border-red-500 text-red-700 dark:text-red-400'
            }`}>
                {notification.type === 'success' ? (
                    <CheckCircleIcon className="w-5 h-5 mr-2" />
                ) : (
                    <ExclamationCircleIcon className="w-5 h-5 mr-2" />
                )}
                <span className="font-medium text-sm">{notification.message}</span>
            </div>
        )}

        <style>{`
          @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
          }
          .animate-fade-in {
            animation: fadeIn 0.4s ease-out forwards;
          }
           @keyframes bounceIn {
            0% { opacity: 0; transform: scale(0.9) translateY(20px); }
            70% { transform: scale(1.05) translateY(-5px); }
            100% { opacity: 1; transform: scale(1) translateY(0); }
          }
          .animate-bounce-in {
            animation: bounceIn 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards;
          }
        `}</style>
    </div>
  );
};

export default App;
